// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PDKS.Data.Context;

#nullable disable

namespace PDKS.Data.Migrations
{
    [DbContext(typeof(PDKSDbContext))]
    partial class PDKSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PDKS.Data.Entities.Avans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("KalanBorc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OdemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("OdendiMi")
                        .HasColumnType("boolean");

                    b.Property<string>("OnayDurumu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OnaylayanKullaniciId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<string>("RedNedeni")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("TaksitSayisi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TalepTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OnaylayanKullaniciId");

                    b.HasIndex("PersonelId");

                    b.ToTable("Avanslar");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Bildirim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Mesaj")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("Okundu")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("OkunmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tip")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Bildirimler");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Cihaz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CihazAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cihaz_adi");

                    b.Property<bool>("Durum")
                        .HasColumnType("boolean")
                        .HasColumnName("durum");

                    b.Property<string>("IPAdres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_adres");

                    b.Property<string>("Lokasyon")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lokasyon");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("olusturma_tarihi");

                    b.Property<int?>("SirketId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SonBaglantiZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("son_baglanti_zamani");

                    b.HasKey("Id");

                    b.HasIndex("SirketId");

                    b.ToTable("cihazlar");
                });

            modelBuilder.Entity("PDKS.Data.Entities.CihazLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Basarili")
                        .HasColumnType("boolean")
                        .HasColumnName("basarili");

                    b.Property<int>("CihazId")
                        .HasColumnType("integer")
                        .HasColumnName("cihaz_id");

                    b.Property<int?>("CihazId1")
                        .HasColumnType("integer");

                    b.Property<string>("Detay")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("detay");

                    b.Property<string>("Islem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("islem");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tarih");

                    b.HasKey("Id");

                    b.HasIndex("CihazId");

                    b.HasIndex("CihazId1");

                    b.ToTable("cihaz_loglari");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Departman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<bool>("Durum")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SirketId")
                        .HasColumnType("integer");

                    b.Property<int?>("UstDepartmanId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SirketId");

                    b.HasIndex("UstDepartmanId");

                    b.ToTable("Departmanlar");
                });

            modelBuilder.Entity("PDKS.Data.Entities.GirisCikis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CihazId")
                        .HasColumnType("integer");

                    b.Property<int?>("CihazId1")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CikisZamani")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ElleGiris")
                        .HasColumnType("boolean");

                    b.Property<int?>("ErkenCikisSuresi")
                        .HasColumnType("integer");

                    b.Property<int?>("FazlaMesaiSuresi")
                        .HasColumnType("integer");

                    b.Property<int?>("GecKalmaSuresi")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GirisZamani")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Not")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CihazId");

                    b.HasIndex("CihazId1");

                    b.HasIndex("GirisZamani");

                    b.HasIndex("PersonelId", "GirisZamani");

                    b.ToTable("GirisCikislar");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Izin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IzinGunSayisi")
                        .HasColumnType("integer");

                    b.Property<string>("IzinTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OnayDurumu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OnaylayanKullaniciId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<string>("RedNedeni")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("TalepTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OnaylayanKullaniciId");

                    b.HasIndex("PersonelId");

                    b.ToTable("Izinler");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SifreHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PersonelId")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Detay")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("detay");

                    b.Property<string>("IpAdres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_adres");

                    b.Property<string>("Islem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("islem");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("integer")
                        .HasColumnName("kullanici_id");

                    b.Property<string>("Modul")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("modul");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tarih");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("loglar");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Mesai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<TimeSpan>("BaslangicSaati")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("BitisSaati")
                        .HasColumnType("interval");

                    b.Property<decimal>("FazlaMesaiSaati")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HaftaSonuMesaiSaati")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MesaiTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OnayDurumu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OnaylayanKullaniciId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<string>("RedNedeni")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("ResmiTatilMesaiSaati")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ToplamSaat")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OnaylayanKullaniciId");

                    b.HasIndex("PersonelId");

                    b.ToTable("Mesailer");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Parametre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Birim")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kategori")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.ToTable("Parametreler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Haftalık standart çalışma günü sayısı",
                            Ad = "Haftalık Çalışma Günü",
                            Birim = "gün",
                            Deger = "5",
                            Kategori = "Çalışma Saatleri",
                            KayitTarihi = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Günlük standart çalışma saati",
                            Ad = "Günlük Çalışma Saati",
                            Birim = "saat",
                            Deger = "8",
                            Kategori = "Çalışma Saatleri",
                            KayitTarihi = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "İşe geç kalma tolerans süresi",
                            Ad = "Geç Kalma Toleransı",
                            Birim = "dakika",
                            Deger = "15",
                            Kategori = "Toleranslar",
                            KayitTarihi = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Erken çıkış tolerans süresi",
                            Ad = "Erken Çıkış Toleransı",
                            Birim = "dakika",
                            Deger = "15",
                            Kategori = "Toleranslar",
                            KayitTarihi = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "Fazla mesai ücreti çarpanı",
                            Ad = "Fazla Mesai Çarpanı",
                            Birim = "kat",
                            Deger = "1.5",
                            Kategori = "Mesai",
                            KayitTarihi = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Aciklama = "Hafta sonu mesai ücreti çarpanı",
                            Ad = "Hafta Sonu Mesai Çarpanı",
                            Birim = "kat",
                            Deger = "2",
                            Kategori = "Mesai",
                            KayitTarihi = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Aciklama = "Yıllık ücretli izin günü sayısı",
                            Ad = "Yıllık İzin Günü",
                            Birim = "gün",
                            Deger = "14",
                            Kategori = "İzin",
                            KayitTarihi = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PDKS.Data.Entities.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Adres")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("AvansLimiti")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CikisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cinsiyet")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("DepartmanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Durum")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gorev")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KanGrubu")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Maas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notlar")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SicilNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SirketId")
                        .HasColumnType("integer")
                        .HasColumnName("sirket_id");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Unvan")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("VardiyaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmanId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SicilNo")
                        .IsUnique();

                    b.HasIndex("SirketId");

                    b.HasIndex("VardiyaId");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Prim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Ay")
                        .HasColumnType("integer");

                    b.Property<string>("Donem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("OdendiMi")
                        .HasColumnType("boolean");

                    b.Property<string>("OnayDurumu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OnaylayanKullaniciId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<string>("PrimAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrimTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Yil")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OnaylayanKullaniciId");

                    b.HasIndex("PersonelId");

                    b.ToTable("Primler");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Roller");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Sistem Yöneticisi",
                            RolAdi = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "İnsan Kaynakları",
                            RolAdi = "IK"
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Departman Yöneticisi",
                            RolAdi = "Yönetici"
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Çalışan",
                            RolAdi = "Personel"
                        });
                });

            modelBuilder.Entity("PDKS.Data.Entities.Sirket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("adres");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean")
                        .HasColumnName("aktif");

                    b.Property<bool>("AnaSirket")
                        .HasColumnType("boolean")
                        .HasColumnName("ana_sirket");

                    b.Property<int?>("AnaSirketId")
                        .HasColumnType("integer")
                        .HasColumnName("ana_sirket_id");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("guncelleme_tarihi");

                    b.Property<string>("Il")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("il");

                    b.Property<string>("Ilce")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ilce");

                    b.Property<DateTime?>("KurulusTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kurulis_tarihi");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Notlar")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notlar");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("olusturma_tarihi");

                    b.Property<string>("ParaBirimi")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("para_birimi");

                    b.Property<string>("PostaKodu")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("posta_kodu");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefon");

                    b.Property<string>("TicariUnvan")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ticari_unvan");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unvan");

                    b.Property<string>("VergiDairesi")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vergi_dairesi");

                    b.Property<string>("VergiNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("vergi_no");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("website");

                    b.HasKey("Id");

                    b.HasIndex("AnaSirketId");

                    b.ToTable("sirketler");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Tatil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("aciklama");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ad");

                    b.Property<bool>("ResmiTatil")
                        .HasColumnType("boolean")
                        .HasColumnName("resmi_tatil");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tarih");

                    b.HasKey("Id");

                    b.HasIndex("Tarih")
                        .IsUnique();

                    b.ToTable("tatiller");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Vardiya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<TimeSpan>("BaslangicSaati")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("BitisSaati")
                        .HasColumnType("interval");

                    b.Property<bool>("Durum")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsnekVardiyaMi")
                        .HasColumnType("boolean");

                    b.Property<bool>("GeceVardiyasiMi")
                        .HasColumnType("boolean");

                    b.Property<int>("ToleransSuresiDakika")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Vardiyalar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Standart gündüz vardiyası 08:00-17:00",
                            Ad = "Gündüz Vardiyası",
                            BaslangicSaati = new TimeSpan(0, 8, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 17, 0, 0, 0),
                            Durum = true,
                            EsnekVardiyaMi = false,
                            GeceVardiyasiMi = false,
                            ToleransSuresiDakika = 15
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Gece vardiyası 20:00-05:00",
                            Ad = "Gece Vardiyası",
                            BaslangicSaati = new TimeSpan(0, 20, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 5, 0, 0, 0),
                            Durum = true,
                            EsnekVardiyaMi = false,
                            GeceVardiyasiMi = true,
                            ToleransSuresiDakika = 15
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Esnek çalışma saatleri",
                            Ad = "Esnek Çalışma",
                            BaslangicSaati = new TimeSpan(0, 9, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 18, 0, 0, 0),
                            Durum = true,
                            EsnekVardiyaMi = true,
                            GeceVardiyasiMi = false,
                            ToleransSuresiDakika = 30
                        });
                });

            modelBuilder.Entity("PDKS.Data.Entities.Avans", b =>
                {
                    b.HasOne("PDKS.Data.Entities.Kullanici", "OnaylayanKullanici")
                        .WithMany()
                        .HasForeignKey("OnaylayanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PDKS.Data.Entities.Personel", "Personel")
                        .WithMany("Avanslar")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OnaylayanKullanici");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Bildirim", b =>
                {
                    b.HasOne("PDKS.Data.Entities.Kullanici", "Kullanici")
                        .WithMany("Bildirimler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Cihaz", b =>
                {
                    b.HasOne("PDKS.Data.Entities.Sirket", null)
                        .WithMany("Cihazlar")
                        .HasForeignKey("SirketId");
                });

            modelBuilder.Entity("PDKS.Data.Entities.CihazLog", b =>
                {
                    b.HasOne("PDKS.Data.Entities.Cihaz", "Cihaz")
                        .WithMany()
                        .HasForeignKey("CihazId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PDKS.Data.Entities.Cihaz", null)
                        .WithMany("CihazLoglari")
                        .HasForeignKey("CihazId1");

                    b.Navigation("Cihaz");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Departman", b =>
                {
                    b.HasOne("PDKS.Data.Entities.Sirket", "Sirket")
                        .WithMany("Departmanlar")
                        .HasForeignKey("SirketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PDKS.Data.Entities.Departman", "UstDepartman")
                        .WithMany("AltDepartmanlar")
                        .HasForeignKey("UstDepartmanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Sirket");

                    b.Navigation("UstDepartman");
                });

            modelBuilder.Entity("PDKS.Data.Entities.GirisCikis", b =>
                {
                    b.HasOne("PDKS.Data.Entities.Cihaz", "Cihaz")
                        .WithMany()
                        .HasForeignKey("CihazId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PDKS.Data.Entities.Personel", "Personel")
                        .WithMany("GirisCikislar")
                        .HasForeignKey("CihazId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PDKS.Data.Entities.Cihaz", null)
                        .WithMany("GirisCikislar")
                        .HasForeignKey("CihazId1");

                    b.Navigation("Cihaz");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Izin", b =>
                {
                    b.HasOne("PDKS.Data.Entities.Kullanici", "OnaylayanKullanici")
                        .WithMany()
                        .HasForeignKey("OnaylayanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PDKS.Data.Entities.Personel", "Personel")
                        .WithMany("Izinler")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OnaylayanKullanici");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Kullanici", b =>
                {
                    b.HasOne("PDKS.Data.Entities.Personel", "Personel")
                        .WithOne("Kullanici")
                        .HasForeignKey("PDKS.Data.Entities.Kullanici", "PersonelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PDKS.Data.Entities.Rol", "Rol")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Log", b =>
                {
                    b.HasOne("PDKS.Data.Entities.Kullanici", "Kullanici")
                        .WithMany("Loglar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Mesai", b =>
                {
                    b.HasOne("PDKS.Data.Entities.Kullanici", "OnaylayanKullanici")
                        .WithMany()
                        .HasForeignKey("OnaylayanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PDKS.Data.Entities.Personel", "Personel")
                        .WithMany("Mesailer")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OnaylayanKullanici");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Personel", b =>
                {
                    b.HasOne("PDKS.Data.Entities.Departman", "Departman")
                        .WithMany("Personeller")
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PDKS.Data.Entities.Sirket", "Sirket")
                        .WithMany("Personeller")
                        .HasForeignKey("SirketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PDKS.Data.Entities.Vardiya", "Vardiya")
                        .WithMany("Personeller")
                        .HasForeignKey("VardiyaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Departman");

                    b.Navigation("Sirket");

                    b.Navigation("Vardiya");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Prim", b =>
                {
                    b.HasOne("PDKS.Data.Entities.Kullanici", "OnaylayanKullanici")
                        .WithMany()
                        .HasForeignKey("OnaylayanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PDKS.Data.Entities.Personel", "Personel")
                        .WithMany("Primler")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OnaylayanKullanici");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Sirket", b =>
                {
                    b.HasOne("PDKS.Data.Entities.Sirket", "AnaSirketNavigation")
                        .WithMany("BagliSirketler")
                        .HasForeignKey("AnaSirketId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AnaSirketNavigation");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Cihaz", b =>
                {
                    b.Navigation("CihazLoglari");

                    b.Navigation("GirisCikislar");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Departman", b =>
                {
                    b.Navigation("AltDepartmanlar");

                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Kullanici", b =>
                {
                    b.Navigation("Bildirimler");

                    b.Navigation("Loglar");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Personel", b =>
                {
                    b.Navigation("Avanslar");

                    b.Navigation("GirisCikislar");

                    b.Navigation("Izinler");

                    b.Navigation("Kullanici");

                    b.Navigation("Mesailer");

                    b.Navigation("Primler");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Rol", b =>
                {
                    b.Navigation("Kullanicilar");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Sirket", b =>
                {
                    b.Navigation("BagliSirketler");

                    b.Navigation("Cihazlar");

                    b.Navigation("Departmanlar");

                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("PDKS.Data.Entities.Vardiya", b =>
                {
                    b.Navigation("Personeller");
                });
#pragma warning restore 612, 618
        }
    }
}
